version: 2
updates:
  - package-ecosystem: maven
    directory: /server
    schedule:
      interval: weekly
    groups:
      maven-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directories: [/server, /web]
    schedule:
      interval: monthly
